# Generated by Django 6.0 on 2026-02-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='phone',
            field=models.CharField(max_length=12),
        ),
    ]
