# Generated by Django 6.0 on 2026-02-25 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_doctorprofile_is_approved_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
