# Generated by Django 6.0 on 2026-03-05 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_department_alter_patientprofile_age_appointment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='available_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='available_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.department'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='experience',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
