# Generated by Django 5.2.7 on 2026-05-18 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_appointment_options_alter_appointment_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=255)),
                ('instructions', models.TextField()),
                ('status', models.CharField(default='pending', max_length=50)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.appointment')),
            ],
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='test_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.testrequest'),
        ),
    ]
