# Generated by Django 5.2.7 on 2026-05-30 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_alter_appointment_id_alter_department_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('uploaded', 'Uploaded'), ('completed', 'Completed')], default='pending', max_length=50),
        ),
    ]
