# Generated by Django 5.2.7 on 2026-06-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_appointment_requested_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='old_appointment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='old_appointment_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='rescheduled',
            field=models.BooleanField(default=False),
        ),
    ]
